Wisky.SkyAdmin.Manage/Wisky.SkyAdmin.Manage/Areas/CRM/Controllers/TransactionController.cs
using HmsService.Models;
using HmsService.Sdk;
using HmsService.ViewModels;
using SkyWeb.DatVM.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Wisky.SkyAdmin.Manage.Areas.CRM.Controllers
{
    public class TransactionController : BaseController
    {
        // GET: CRM/Transaction
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult TransactionDetail(int id, int customerId)
        {
            var accApi = new AccountApi();
            var membershipCardApi = new MembershipCardApi();
            var customerApi = new CustomerApi();

            var customer = customerApi.GetCustomerById(customerId);
            CustomerEditViewModel model = new CustomerEditViewModel(customer.ToEntity());
            model.MembershipCard = membershipCardApi.GetMembershipCardById(id);
            model.AllAccounts = accApi.GetAccountsByMembershipCardId(id).Select(a => new SelectListItem
            {
                Text = a.AccountName,
                Value = a.AccountID.ToString(),
            });

            return View(model);
        }


        public JsonResult LoadTransaction(JQueryDataTableParamModel param, int brandId, int transactionStatus, int transactionType, string startDate, string endDate)
        {
            var transactionApi = new TransactionApi();
            var accountApi = new AccountApi();
            var customerApi = new CustomerApi();
            var membershipCardApi = new MembershipCardApi();


            var startTime = startDate.ToDateTime().GetStartOfDate();
            var endTime = endDate.ToDateTime().GetEndOfDate();
            var transaction = transactionApi.GetAllBrandByTimeRange(brandId, startTime, endTime).AsEnumerable<TransactionViewModel>();
            var customerAPi = new CustomerApi();
            //if (accountId != -1)
            //{
            //    transaction = transaction.Where(q => q.AccountId == accountId);
            //}
            try
            {
                var count = param.iDisplayStart + 1;
                if (!string.IsNullOrEmpty(param.sSearch))
                {
                   transaction = transaction.Where(a => membershipCardApi.Get(accountApi.Get(a.AccountId).MembershipCardId.Value).MembershipCardCode.Contains(param.sSearch.ToLower())
                    );
                }
                if (transactionStatus != -1)
                {
                    transaction = transaction.Where(a => a.Status == transactionStatus);
                }
                if (transactionType != -1)
                {
                    transaction = transaction.Where(a => a.IsIncreaseTransaction == (transactionType ==0));
                }
                var totalRecords = transaction.Count();
                var totalDisplayRecords = transaction.Count();
                var rs = transaction
                    .OrderByDescending(q => q.Date)
                    .Skip(param.iDisplayStart)
                    .Take(param.iDisplayLength)
                    .ToList()
                    .Select(a => new IConvertible[]
                    {
                            count++,
                            membershipCardApi.GetMembershipCardById(accountApi.Get(a.AccountId)
                            .MembershipCardId.GetValueOrDefault()).MembershipCardCode,                      
                            membershipCardApi.GetMembershipCardById(accountApi.Get(a.AccountId)
                            .MembershipCardId.GetValueOrDefault()).CustomerName,
                            a.Amount,
                            a.Date.ToString("dd/MM/yyyy HH:mm:ss"),
                            string.IsNullOrWhiteSpace(a.Notes) ? "---" : a.Notes,
                            a.StoreId <=0 ? "Hệ Thống" : (Utils.GetStore(a.StoreId).Name), 
                            a.Status,
                            a.Id,
                            membershipCardApi.GetMembershipCardById(accountApi.Get(a.AccountId)
                            .MembershipCardId.GetValueOrDefault()).CustomerId,
                            a.IsIncreaseTransaction
                           // a.Id,
                            //a.Account.Type
                    });
                var list2 = transaction
                    .ToList()
                    .Select(a => new IConvertible[]
                    {
                            a.Amount,
                            a.Status,
                            a.IsIncreaseTransaction
                    });
                return Json(new
                {
                    sEcho = param.sEcho,
                    iTotalRecords = totalRecords,
                    iTotalDisplayRecords = totalDisplayRecords,
                    aaData = rs,
                    totalData = list2,
                }, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json(new { success = false, message = "Error" });
            }
        }

        //public ActionResult Create(int Id)
        //{
        //    TransactionEditViewModel model = new TransactionEditViewModel();
        //    model.AccountId = Id;
        //    model.IsIncreaseTransaction = true;
        //    return View(model);
        //}
        public ActionResult CreateByAccountId(int id)
        {
            var model = new TransactionEditViewModel();
            var accountApi = new AccountApi();
            var account = accountApi.GetAccountEntityById(id);
            model.AccountId = account.AccountID;
            model.Amount = (int)account.Balance;
            return View(model);
        }
        [HttpPost]
        public async Task<JsonResult> CreateByAccountId(TransactionEditViewModel model)
        {
            var brandId = int.Parse(RouteData.Values["brandId"].ToString());
            var transactionApi = new TransactionApi();
            var accountApi = new AccountApi();
            var membershipCardApi = new MembershipCardApi();
            var account = await accountApi.GetAsync(model.AccountId);
            if (model.Amount == 0 || model.Amount.ToString().Length > 9)
            {
                return Json(new { success = false, message = "Số tiền tăng hoặc giảm cần lớn hơn 0 và cần ít hơn 9 chữ số!" },
                    JsonRequestBehavior.AllowGet);
            }
            model.Amount = (decimal)model.Amount;
            model.Status = (int)TransactionStatus.New;
            var customerId = membershipCardApi.GetMembershipCardById(account.MembershipCardId.GetValueOrDefault()).CustomerId;
            var customer = (new CustomerApi()).GetCustomerEntityById(customerId);
            await transactionApi.CreateTransactionAsync(model, customer, brandId);
            account = await accountApi.GetAsync(model.AccountId);
            return Json(new { success = true, message = "Tạo giao dịch thành công!", balance = account.Balance }, JsonRequestBehavior.AllowGet);
        }
        //public ActionResult Create(int Id)
        //{
        //    TransactionEditViewModel model = new TransactionEditViewModel();
        //    AccountApi accountApi = new AccountApi();
        //    model.ActiveAccounts = accountApi.GetActiveAccountByCusId(Id);
        //    model.IsIncreaseTransaction = true;
        //    return PartialView(model);
        //}

        public ActionResult Create(int id)
        {
            TransactionEditViewModel model = new TransactionEditViewModel();
            AccountApi accountApi = new AccountApi();
            model.ActiveAccounts = accountApi.GetActiveAccountByCardId(id);
            model.IsIncreaseTransaction = true;
            return PartialView(model);
        }

        //[HttpPost]
        //public async Task<ActionResult> Create(TransactionEditViewModel model)
        //{
        //    if (!this.ModelState.IsValid)
        //    {
        //        return View(model);
        //    }
        //    var transactionApi = new TransactionApi();
        //    var accountApi = new AccountApi();
        //    var account = await accountApi.GetAsync(model.AccountId);
        //    if ((account.Balance == 0 || account.Balance==null ||account.Balance < model.Amount) && model.IsIncreaseTransaction==false)
        //    {
        //        TempData["msg"] = "<script>alert('Số dư của tài khoản hiện đang bé hơn số tiền giảm!');</script>";

        //        return RedirectToAction("CustomerDetail", "Customer", new { Id = account.CustomerID });
        //    }
        //    await transactionApi.CreateTransactionAsync(model);
        //    return RedirectToAction("CustomerDetail", "Customer", new { Id = account.CustomerID });
        //}

        [HttpPost]
        public async Task<JsonResult> Create(TransactionEditViewModel model)
        {
            var transactionApi = new TransactionApi();
            var accountApi = new AccountApi();
            var storeApi = new StoreApi();
            var store = storeApi.Get(model.StoreId);
            var account = await accountApi.GetAsync(model.AccountId);
            if (model.Amount == 0 || model.Amount.ToString().Length > 9)
            {
                return Json(new { success = false, message = "Số tiền tăng hoặc giảm cần lớn hơn 0 và cần ít hơn 9 chữ số!" },
                    JsonRequestBehavior.AllowGet);
            }
            //if ((account.Balance == null || account.Balance < double.Parse(model.Amount.ToString())) && model.IsIncreaseTransaction == false)
            //{
            //    return Json(new { success = false, message = "Số dư của tài khoản hiện đang bé hơn số tiền giảm!" },
            //        JsonRequestBehavior.AllowGet);
            //}
            model.Amount = (decimal)model.Amount;
            model.StoreId = store.ID;
            model.Status = (int)TransactionStatus.Approve;

Wisky.SkyAdmin.Manage/Wisky.SkyAdmin.Manage/Areas/CRM/Views/Transaction/Create.cshtml
@model HmsService.ViewModels.TransactionEditViewModel

@{
    ViewBag.Title = "Tạo giao dịch";
    Layout = null;
}

@Html.ValidationSummary()
<div class="modal-dialog modal-md">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close btn btn-danger" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h3 class="modal-title">Thêm giao dịch</h3>
        </div>
        <form id="formTransaction" method="post">
            <div class="modal-body">
                <div class="form-horizontal">
                    <div class="row group-info" style="margin-left:-2px; margin-right:-2px;">
                        <div class="form-group">
                            <label class="control-label col-md-4" for="Amount">Tài khoản<span style="color:red"></span></label>
                            <div class="col-md-6">
                                @*<select class="selectpicker" id="selectedAccount" style="display:block!important" onload="selectPicker()" onchange="selectPickerChoose()">
                                        @foreach (var item in Model.ActiveAccounts)
                                        {
                                            <option value="@item.AccountID">@item.AccountName</option>
                                        }
                                    </select>*@
                                @Html.DropDownListFor(q => q.AccountId, (Model.ActiveAccounts).Select(e => new SelectListItem { Text = e.AccountName, Value = e.AccountID.ToString() }), new { id = "transactionAccountId", @class = "form-control fg-line" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4" for="RecentAmount" id="labelRecentAmount">Số tiền hiện tại<span style="color:red"></span></label>
                            <div class="col-md-6">
                                <input class="form-control fg-line" id="RecentAmount" readonly/>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4" for="Amount" id="labelAmount">Số tiền<span style="color:red"></span></label>
                            <div class="col-md-6">
                                @Html.TextBoxFor(q => q.Amount, new { @type = "number", @min = 0, id = "Amount", @class = "form-control fg-line", placeholder = "Nhập số tiền", required = "required", oninput = "correctAmount()", Value = ""})
                            </div>
                        </div>
                        <div class="form-group" hidden>
                            <label class="control-label col-md-4" for="AccountName">Tiền tệ<span style="color:red"></span></label>
                            <div class="col-md-6">
                                @Html.DropDownListFor(q => q.CurrencyCode, Enum.GetNames(typeof(Currency)).Select(e => new SelectListItem { Text = e }), new { @class = "form-control fg-line" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4" for="FCAmount">FCAmount<span style="color:red"></span></label>
                            <div class="col-md-6">
                                @Html.TextBoxFor(q => q.FCAmount, new { @type = "number", @min = 0, id = "FCAmount", @class = "form-control fg-line", required = "required", oninput = "correctFCAmount()", Value = "", @readonly = "readonly" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label">Ngày giao dịch</label>
                            <div class="col-md-6">
                                <input class="form-control fg-line" type="text" name="Date" value="@(String.Format("{0:MM/dd/yyyy}",DateTime.Now))" readonly style="background-color:#ffffff; color:#000000;" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4" for="Notes">Ghi chú</label>
                            <div class="col-md-6">
                                @Html.TextBoxFor(q => q.Notes, new { id = "Notes", @class = "form-control fg-line", placeholder = "Nhập chú thích nếu có" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4" for="IsIncreaseTransaction">Loại giao dịch</label>
                            <div class="col-md-6">
                                <select class="form-control fg-line" name="IsIncreaseTransaction" id="IsIncreaseTransaction">
                                    <option value="true">Tăng</option>
                                    <option value="false">Giảm</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <a data-dismiss="modal" class="btn btn-primary">Đóng</a>
                <button type="button" onclick="createTransaction()" class="btn btn-success">Thêm</button>
            </div>
        </form>
    </div>
</div>
<style>
    .daterangepicker {
        margin-top: initial !important;
    }
</style>
<script>
    function CheckAccount() {
        $.ajax({
            type: 'GET',
            url: '@Url.Action("CheckAccount","Transaction")',
            data: {'accountId' : $('#transactionAccountId').val()},
            //async: false,
            success: function (result) {
                if (result.typeId == 1) {
                    $('#labelAmount').html('Số tiền thêm');
                    document.getElementById("Amount").setAttribute("placeholder", 'nhập số tiền');
                    $('#labelRecentAmount').html('Số tiền hiện tại');
                }
                if (result.typeId == 2) {
                    $('#labelAmount').html('Số sản phẩm thêm');
                    document.getElementById("Amount").setAttribute("placeholder", 'nhập số sản phẩm');
                    $('#labelRecentAmount').html('Số sản phẩm hiện tại');
                }
                if (result.typeId == 3) {
                    $('#labelAmount').html('Số điểm');
                    document.getElementById("Amount").setAttribute("placeholder", 'nhập số điểm');
                    $('#labelRecentAmount').html('Số điểm hiện tại');
                }
                document.getElementById('RecentAmount').setAttribute('value', result.balance);
            },
        });
    };
    $('#transactionAccountId').change(CheckAccount());
    $('#transactionAccountId').change(function () {
        CheckAccount();
    });
    $('#Amount').keyup(function () {
        FCAmountEvent();
    });
    $('#IsIncreaseTransaction').change(function () {
        FCAmountEvent();
    });
    function FCAmountEvent() {
        if ($('#IsIncreaseTransaction').val() == 'true' ) {
            var i = parseInt($('#Amount').val()) + parseInt($('#RecentAmount').val());
        } else{
            var i = parseInt($('#RecentAmount').val()) - parseInt($('#Amount').val());
        }
        $('#FCAmount').val(i);
    }
    
    $(function () {
        @if (Model.Date != DateTime.MinValue) {
            <text>

        var start = moment('@Model.Date.ToString("MM/dd/yyyy")').format("DD/MM/YYYY");
        </text>
        }
        else
        {
            <text>
        var start = moment().add(0, 'days');
        $('#reportrange span').html(start.format('DD/MM/YYYY'));
        //$('#reportrange span').html(moment().add(-30, 'days').format('MMM D, YYYY') + ' - ' + moment().add(0, 'days').format('MMM D, YYYY'));
        </text>
        }
        $('input[name="Date"]').daterangepicker({
            format: "MM/DD/YYYY",
            singleDatePicker: true,
            showDropdowns: true,
            startDate: moment(),
            locale: {
                "format": "DD/MM/YYYY"
            }
        },
        function (start, end, label) {
            var years = moment().diff(start, 'years');
            $('#reportrange span').html(start.format('DD/MM/YYYY'));
        });
    });

    @if(this.Model.IsIncreaseTransaction == true)
    {
        <text>
    $('#IsIncreaseTransaction').val("true");
    </text>
    }
    else
    {
        <text>
    $('#IsIncreaseTransaction').val("false");
    </text>
    }
    function correctAmount() {
        var amount = $('#Amount').val().replace(/[^\d]/g, '');
        $('#Amount').val(amount);
    }

    function correctFCAmount() {
        var amount = $('#FCAmount').val().replace(/[^\d]/g, '');
        $('#FCAmount').val(amount);
    }

    function createTransaction() {
        var formData = $("#formTransaction").serialize();
        $.ajax({
            type: "Post",
            url: '@(Url.Action("Create", "Transaction"))',
            data: formData,
            success: function (result) {
                if (result.success) {
                    // Đóng modal
                    $('#createTransactionPanel').modal('hide');
                    $('body').removeClass('modal-open');
                    $('.modal-backdrop').remove();

                    // Kiểm tra tài khoản mặc định có giống tài khoản đang giao dịch hay không,
                    // nếu phải thì update lại balance sau khi giao dịch.
                    var defaultId = $('#defaultAccountId').val();
                    var transId = $('#transactionAccountId').val();

                    if (defaultId == transId) {
                        $("#defaultAccountBalance").val(result.balance);

                        if (result.balance == '') {
                            result.balance = '0';
                        }
                        $("#dAccBalance").html('Số dư tài khoản: ' + result.balance.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ","));
                        $("#defaultAccountBalance2").html(result.balance.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ","));
                    }

                    ShowMessage(result.message, 2);
                    RefresTransactionTable();
                } else {
                    ShowMessage(result.message, 1);
                }


            },
            error: function (error) {
                ShowMessage("Có lỗi xảy ra", 1);
            }
        });
    }
</script>

Wisky.SkyAdmin.Manage/Wisky.SkyAdmin.Manage/Areas/CRM/Views/Transaction/CreateByAccountId.cshtml
@model HmsService.ViewModels.TransactionEditViewModel

@{
    ViewBag.Title = "Tạo giao dịch";
    Layout = null;
}

@Html.ValidationSummary()
<div class="modal-dialog modal-md">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close btn btn-danger" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h3 class="modal-title">Thêm giao dịch</h3>
        </div>
        <form id="formTransaction" method="post">
            <div class="modal-body">
                <div class="form-horizontal">
                    <div class="row group-info" style="margin-left:-2px; margin-right:-2px;">
                        <div class="form-group">
                            <label class="control-label col-md-4" for="Amount">Tài khoản<span style="color:red"></span></label>
                            <div class="col-md-6">
                                @*<select class="selectpicker" id="selectedAccount" style="display:block!important" onload="selectPicker()" onchange="selectPickerChoose()">
                                        @foreach (var item in Model.ActiveAccounts)
                                        {
                                            <option value="@item.AccountID">@item.AccountName</option>
                                        }
                                    </select>*@
                                @*@Html.DropDownListFor(q => q.AccountId, (Model.ActiveAccounts).Select(e => new SelectListItem { Text = e.AccountName, Value = e.AccountID.ToString() }), new { id = "transactionAccountId", @class = "form-control fg-line" })*@
                                @Html.TextBoxFor(q => q.AccountId, new { @type = "number", id = "transactionAccountId", @class = "form-control fg-line", Value = Model.AccountId })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4" for="RecentAmount" id="labelRecentAmount">Số tiền hiện tại<span style="color:red"></span></label>
                            <div class="col-md-6">
                                <input class="form-control fg-line" id="RecentAmount" readonly value="@Model.Amount"/>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4" for="Amount" id="labelAmount">Số tiền<span style="color:red"></span></label>
                            <div class="col-md-6">
                                @Html.TextBoxFor(q => q.Amount, new { @type = "number", @min = 0, id = "Amount", @class = "form-control fg-line", placeholder = "Nhập số tiền", required = "required", oninput = "correctAmount()", Value = "" })
                            </div>
                        </div>
                        <div class="form-group" hidden>
                            <label class="control-label col-md-4" for="AccountName">Tiền tệ<span style="color:red"></span></label>
                            <div class="col-md-6">
                                @Html.DropDownListFor(q => q.CurrencyCode, Enum.GetNames(typeof(Currency)).Select(e => new SelectListItem { Text = e }), new { @class = "form-control fg-line" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4" for="FCAmount">FCAmount<span style="color:red"></span></label>
                            <div class="col-md-6">
                                @Html.TextBoxFor(q => q.FCAmount, new { @type = "number", @min = 0, id = "FCAmount", @class = "form-control fg-line", required = "required", oninput = "correctFCAmount()", Value = "", @readonly = "readonly" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label">Ngày giao dịch</label>
                            <div class="col-md-6">
                                <input class="form-control fg-line" type="text" name="Date" value="@(String.Format("{0:MM/dd/yyyy}",DateTime.Now))" readonly style="background-color:#ffffff; color:#000000;" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4" for="Notes">Ghi chú</label>
                            <div class="col-md-6">
                                @Html.TextBoxFor(q => q.Notes, new { id = "Notes", @class = "form-control fg-line", placeholder = "Nhập chú thích nếu có" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4" for="IsIncreaseTransaction">Loại giao dịch</label>
                            <div class="col-md-6">
                                <select class="form-control fg-line" name="IsIncreaseTransaction" id="IsIncreaseTransaction">
                                    <option value="true">Tăng</option>
                                    <option value="false">Giảm</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <a data-dismiss="modal" class="btn btn-primary">Đóng</a>
                <button type="button" onclick="createTransaction()" class="btn btn-success">Thêm</button>
            </div>
        </form>
    </div>
</div>
<style>
    .daterangepicker {
        margin-top: initial !important;
    }
</style>
<script>
    function CheckAccount() {
        $.ajax({
            type: 'GET',
            url: '@Url.Action("CheckAccount","Transaction")',
            data: {'accountId' : $('#transactionAccountId').val()},
            //async: false,
            success: function (result) {
                if (result.typeId == 1) {
                    $('#labelAmount').html('Số tiền thêm');
                    document.getElementById("Amount").setAttribute("placeholder", 'nhập số tiền');
                    $('#labelRecentAmount').html('Số tiền hiện tại');
                }
                if (result.typeId == 2) {
                    $('#labelAmount').html('Số sản phẩm thêm');
                    document.getElementById("Amount").setAttribute("placeholder", 'nhập số sản phẩm');
                    $('#labelRecentAmount').html('Số sản phẩm hiện tại');
                }
                if (result.typeId == 3) {
                    $('#labelAmount').html('Số điểm');
                    document.getElementById("Amount").setAttribute("placeholder", 'nhập số điểm');
                    $('#labelRecentAmount').html('Số điểm hiện tại');
                }
                document.getElementById('RecentAmount').setAttribute('value', result.balance);
            },
        });
    };
    $('#transactionAccountId').change(CheckAccount());
    $('#transactionAccountId').change(function () {
        CheckAccount();
    });
    $('#Amount').keyup(function () {
        FCAmountEvent();
    });
    $('#IsIncreaseTransaction').change(function () {
        FCAmountEvent();
    });
    function FCAmountEvent() {
        if ($('#IsIncreaseTransaction').val() == 'true' ) {
            var i = parseInt($('#Amount').val()) + parseInt($('#RecentAmount').val());
        } else{
            var i = parseInt($('#RecentAmount').val()) - parseInt($('#Amount').val());
        }
        $('#FCAmount').val(i);
    }

    $(function () {
        @if (Model.Date != DateTime.MinValue) {
            <text>

        var start = moment('@Model.Date.ToString("MM/dd/yyyy")').format("DD/MM/YYYY");
        </text>
        }
        else
        {
            <text>
        var start = moment().add(0, 'days');
        $('#reportrange span').html(start.format('DD/MM/YYYY'));
        //$('#reportrange span').html(moment().add(-30, 'days').format('MMM D, YYYY') + ' - ' + moment().add(0, 'days').format('MMM D, YYYY'));
        </text>
        }
        $('input[name="Date"]').daterangepicker({
            format: "MM/DD/YYYY",
            singleDatePicker: true,
            showDropdowns: true,
            startDate: moment(),
            locale: {
                "format": "DD/MM/YYYY"
            }
        },
        function (start, end, label) {
            var years = moment().diff(start, 'years');
            $('#reportrange span').html(start.format('DD/MM/YYYY'));
        });
    });

    @if(this.Model.IsIncreaseTransaction == true)
    {
        <text>
    $('#IsIncreaseTransaction').val("true");
    </text>
    }
    else
    {
        <text>
    $('#IsIncreaseTransaction').val("false");
    </text>
    }
    function correctAmount() {
        var amount = $('#Amount').val().replace(/[^\d]/g, '');
        $('#Amount').val(amount);
    }

    function correctFCAmount() {
        var amount = $('#FCAmount').val().replace(/[^\d]/g, '');
        $('#FCAmount').val(amount);
    }

    function createTransaction() {
        var formData = $("#formTransaction").serialize();
        $.ajax({
            type: "Post",
            url: '@(Url.Action("CreateByAccountId", "Transaction"))',
            data: formData,
            success: function (result) {
                if (result.success) {
                    // Đóng modal
                    $('#addBalanceModal').modal('hide');
                    $('body').removeClass('modal-open');
                    $('.modal-backdrop').remove();

                    // Kiểm tra tài khoản mặc định có giống tài khoản đang giao dịch hay không,
                    // nếu phải thì update lại balance sau khi giao dịch.
                    var defaultId = $('#defaultAccountId').val();
                    var transId = $('#transactionAccountId').val();

                    if (defaultId == transId) {
                        $("#defaultAccountBalance").val(result.balance);

                        if (result.balance == '') {
                            result.balance = '0';
                        }
                        $("#dAccBalance").html('Số dư tài khoản: ' + result.balance.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ","));
                        $("#defaultAccountBalance2").html(result.balance.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ","));
                    }

                    ShowMessage(result.message, 2);
                    RefresTransactionTable();
                } else {
                    ShowMessage(result.message, 1);
                }


            },
            error: function (error) {
                ShowMessage("Có lỗi xảy ra", 1);
            }
        });
    }
</script>