Wisky.SkyAdmin.Manage/Wisky.SkyAdmin.Manage/Areas/SysAdmin/Controllers/PosFileController.cs
using HmsService.Models.Entities;
using HmsService.Sdk;
using HmsService.ViewModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Wisky.SkyAdmin.Manage.Areas.SysAdmin.Controllers
{
    public class PosFileController : Controller
    {
        // GET: SysAdmin/PosFile
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetAllPosFile()
        {
            try
            {
                var posFileApi = new PosFileApi();
                var count = 1;
                var list = posFileApi.GetActive().Select(q => new IConvertible[] {
                    count++,
                    q.FileName,
                    q.Version,
                    q.Id
                }).ToList();

                if (list != null && count > 1)
                {
                    return Json(new { success = true, list = list }, JsonRequestBehavior.AllowGet);
                }

                return Json(new { success = false, message = "Bảng không có dữ liệu" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(new { success = false, message = "Có lỗi xảy ra. Xin vui lòng liện hệ Admin." }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetAllConfig(int posFileId)
        {
            try
            {
                var posConfigApi = new PosConfigApi();
                var count = 1;
                var list = posConfigApi.GetAllPosConfigByFileId(posFileId);

                if (list != null && count > 0)
                {
                    return Json(new { success = true, list = list }, JsonRequestBehavior.AllowGet);
                }

                return Json(new { success = false, message = "Không có pos config" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(new { success = false, message = "Có lỗi xảy ra. Xin vui lòng liện hệ Admin." }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public async Task<JsonResult> ConfigPosFileViaLocalFile()
        {
            if (Request.Files.Count > 0)
            {
                var file = Request.Files[0];
                var braceIndex = file.FileName.IndexOfAny(new char[] { '(','.'});
                var fileName = braceIndex >= 0 ? file.FileName.Substring(0, braceIndex).Trim() : file.FileName;
                using (var sr = new StreamReader(file.InputStream))
                using (var jsonTextReader = new JsonTextReader(sr))
                {
                    var posFileApi = new PosFileApi();
                    var storeApi = new StoreApi();
                    var jsonSerializer = new JsonSerializer();
                    var configKeyDict = jsonSerializer.Deserialize<Dictionary<string, string>>(jsonTextReader);
                    var stId = configKeyDict["StoreId"];
                    var version = configKeyDict["Version"];
                    var storeId = 0;
                    int.TryParse(stId, out storeId);
                    var posFile = posFileApi.GetActivePosFileByNameAndStore(fileName, storeId);
                    var posConfigList = new List<PosConfigViewModel>();
                    foreach (var keyValue in configKeyDict)
                    {
                        var posConfigsVM = new PosConfigViewModel
                        {
                            Key = keyValue.Key,
                            Value = keyValue.Value,
                        };
                        posConfigList.Add(posConfigsVM);
                    }
                    if (posFile == null) //ko co' pos file thi tao
                    {
                        var brandId = storeApi.Get(storeId).BrandId.Value;                       
                        var postFileVM = new PosFileViewModel()
                        {
                            FileName = fileName,
                            StoreId = storeId,
                            PosConfigs = posConfigList,
                            BrandId = brandId,
                            Version = version
                        };
                        await posFileApi.CreateAsync(postFileVM);
                        return Json(new { success = true, message = "Cập nhật thành công" }, JsonRequestBehavior.AllowGet);
                    }
                    else // co roi thi update
                    {
                        if(version.CompareTo(posFile.Version) > 0)//neu version dulieu tren DB cu hon thi update
                        {
                            posFile.Version = version;
                            posFile.PosConfigs = posConfigList;
                            if (posFileApi.UpdatePostFileWithAllConfigs(posFile))
                            {
                                return Json(new { success = true, message = "Cập nhật thành công" }, JsonRequestBehavior.AllowGet);
                            }
                        }
                        else
                        {
                            return Json(new { success = true, message = "Phiên bản file update thấp hơn phiên bản hiện tại" }, JsonRequestBehavior.AllowGet);
                        }
                        
                    }
                }
            }
            return Json(new { success = false, message = "Cập nhật fail" }, JsonRequestBehavior.AllowGet);

        }

        public ActionResult Edit(int posFileId)
        {
            var posFileApi = new PosFileApi();
            var posConfigApi = new PosConfigApi();
            var storeApi = new StoreApi();
            var brandApi = new BrandApi();
            //List<PosConfigViewModel> configList = posConfigApi.GetAllPosConfigByFileId(posFileId);
            var model = posFileApi.Get(posFileId);
            var store = new StoreViewModel(storeApi.GetStoreById(model.StoreId.Value));
            var brand = brandApi.GetBrandById(model.BrandId);
            ViewBag.currentStore = store;
            ViewBag.currentBrand = brand;
            ViewBag.StoreList = new List<StoreViewModel>();
            ViewBag.BrandList = new List<BrandViewModel>();
            //model.PosConfigs = configList == null ? new List<PosConfigViewModel>() : configList;
            return this.View(model);
        }

        public ActionResult Create()
        {
            var brandApi = new BrandApi();
            var brandList = brandApi.GetActive().Select(q => new { Id = q.Id, Name = q.BrandName });
            var model = new PosFileViewModel();
            ViewBag.currentStore = null;
            ViewBag.currentBrand = null;
            ViewBag.BrandList = brandList;
            return this.View(model);
        }

        public ActionResult CreatePosFile(PosFileEditViewModel model)
        {
            try
            {
                var posFileApi = new PosFileApi();
                var posConfigApi = new PosConfigApi();
                var createModel = new PosFileViewModel
                {
                    BrandId = model.BrandId,
                    StoreId = model.StoreId,
                    FileName = model.FileName,
                    Version = model.Version
                };

                var posFileId = posFileApi.CreateAndReturnId(createModel);

                if (posFileId != -1)
                {
                    var posConfigList = Newtonsoft.Json.JsonConvert.DeserializeObject<List<PosConfigEditViewModel>>(model.PosConfigList);
                    foreach (var config in posConfigList)
                    {
                        var configModel = new PosConfigViewModel
                        {
                            Key = config.Key,
                            Value = config.Value,
                            PosFileId = posFileId
                        };

                        posConfigApi.Create(configModel);
                    }

                    return Json(new { success = true, message = "Tạo POS file thành công." }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = false, message = "Tạo POS file không thành công." }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception e)
            {
                return Json(new { success = false, message = "Có lỗi xảy ra, xin vui lòng liên hệ admin." }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult EditPosFile(int currentPosFileId, PosFileEditViewModel model)
        {
            try
            {
                var posFileApi = new PosFileApi();
                var posConfigApi = new PosConfigApi();
                var editModel = new PosFileViewModel
                {
                    Id = currentPosFileId,
                    BrandId = model.BrandId,
                    StoreId = model.StoreId,
                    FileName = model.FileName,
                    Version = model.Version
                };

                var isSuccessUpdate = posFileApi.UpdateAndReturnSuccess(editModel);

                if (isSuccessUpdate)
                {
                    var isSuccessDelete = posFileApi.DeleteAllConfigAndReturnSuccess(currentPosFileId);

                    if (isSuccessDelete)
                    {
                        var posConfigList = Newtonsoft.Json.JsonConvert.DeserializeObject<List<PosConfigEditViewModel>>(model.PosConfigList);
                        foreach (var config in posConfigList)
                        {
                            var configModel = new PosConfigViewModel
                            {
                                Key = config.Key,
                                Value = config.Value,

Wisky.SkyAdmin.Manage/Wisky.SkyAdmin.Manage/Areas/SysAdmin/Views/PosFile/Create.cshtml
@model HmsService.ViewModels.PosFileViewModel

@{
    ViewBag.Title = "Create Product";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@this.Html.Partial("Editor", this.Model)


@section scripts {

    <link href="~/Content/plugins/elfinder/css/elfinder.min.css" rel="stylesheet" />
    <link href="~/Content/plugins/elfinder/css/theme.css" rel="stylesheet" />

    <script src="~/Content/plugins/dropzone/dropzone.js"></script>
    <script src="~/Content/plugins/dragsort/jquery.dragsort-0.5.2.min.js"></script>
    <script src="~/Content/plugins/elfinder/js/elfinder.full.js"></script>

    <script>
        $(document).ready(function () {
            SKYWEB.Admin.Product.init();

            $('#btn-submit').on('click', function () {
                var fileName = $('#file-name').val().trim();
                var version = $('#file-version').val().trim();
                var brandId = $('#brandId').val();
                var storeId = $('#storeId').val();
                if (fileName == '') {
                    ShowMessage('Xin nhập tên file!', 3);
                    return;
                }

                if (version == '') {
                    ShowMessage('Xin nhập phiên bản!', 3);
                    return;
                }

                if (version.length > 10) {
                    ShowMessage('Tên phiên bản quá 10 ký tự', 1);
                    return;
                }

                if (brandId == '' || brandId == null) {
                    ShowMessage('Xin hãy chọn 1 thương hiệu!', 3);
                    return;
                }

                if (storeId == '' || storeId == null) {
                    ShowMessage('Xin hãy chọn 1 cửa hàng!', 3);
                    return;
                }

                var keyList = $('input[name=config-key]');
                var valueList = $('input[name=config-value]');
                var configList = [];
                for (var i = 0; i < keyList.length; i++) {
                    if ($(keyList[i]).val().trim() != '' && $(valueList[i]).val().trim() != '') {
                        configList.push({ "Key": $(keyList[i]).val().trim(), "Value": $(valueList[i]).val().trim() });
                    }
                }

                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("CreatePosFile")',
                    data: {
                        "FileName": $('#file-name').val().trim(),
                        "Version": $('#file-version').val().trim(),
                        "StoreId": $('#storeId').val(),
                        "BrandId": $('#brandId').val(),
                        "PosConfigList": JSON.stringify(configList)
                    },
                    success: function (result) {
                        if (result.success) {
                            ShowMessage(result.message, 2);
                            window.location.href = '@Url.Action("Index", "PosFile")';
                        } else {
                            ShowMessage(result.message, 1);
                        }
                    }
                });
            });
        });
    </script>
}

Wisky.SkyAdmin.Manage/Wisky.SkyAdmin.Manage/Areas/SysAdmin/Views/PosFile/Edit.cshtml
@model HmsService.ViewModels.PosFileViewModel

@{
    ViewBag.Title = "Edit Product";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@this.Html.Partial("Editor", this.Model)

@section scripts {

    <link href="~/Content/plugins/elfinder/css/elfinder.min.css" rel="stylesheet" />
    <link href="~/Content/plugins/elfinder/css/theme.css" rel="stylesheet" />

    <script src="~/Content/plugins/dropzone/dropzone.js"></script>
    <script src="~/Content/plugins/dragsort/jquery.dragsort-0.5.2.min.js"></script>
    <script src="~/Content/plugins/elfinder/js/elfinder.full.js"></script>

    <script>
        $(document).ready(function () {
            SKYWEB.Admin.Product.init();

            $('#btn-submit').on('click', function () {
                var fileName = $('#file-name').val().trim();
                var version = $('#file-version').val().trim();
                var brandId = $('#brandId').val();
                var storeId = $('#storeId').val();
                if (fileName == '') {
                    ShowMessage('Xin nhập tên file!', 3);
                    return;
                }

                if (version == '') {
                    ShowMessage('Xin nhập phiên bản!', 3);
                    return;
                }

                if (version.length > 10) {
                    ShowMessage('Tên phiên bản quá 10 ký tự');
                }

                var keyList = $('input[name=config-key]');
                var valueList = $('input[name=config-value]');
                var configList = [];
                for (var i = 0; i < keyList.length; i++) {
                    if ($(keyList[i]).val().trim() != '' && $(valueList[i]).val().trim() != '') {
                        configList.push({"Key": $(keyList[i]).val().trim(), "Value": $(valueList[i]).val().trim()});
                    }
                }

                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("EditPosFile")',
                    data: {
                        "currentPosFileId": @Model.Id,
                        "FileName": $('#file-name').val(),
                        "Version": $('#file-version').val(),
                        "StoreId": $('#storeId').val(),
                        "BrandId": $('#brandId').val(),
                        "PosConfigList": JSON.stringify(configList)
                    },
                    success: function (result) {
                        if (result.success) {
                            ShowMessage(result.message, 2);
                            window.location.href = '@Url.Action("Index", "PosFile")';
                        } else {
                            ShowMessage(result.message, 1);
                        }
                    }
                });
            });
        });
    </script>
}

Wisky.SkyAdmin.Manage/Wisky.SkyAdmin.Manage/Areas/SysAdmin/Views/PosFile/Editor.cshtml
@model HmsService.ViewModels.PosFileViewModel

@{

}

<style>
    .pair-group .btn,
    .variant-group .btn {
        font-weight: 500 !important;
    }

    .col-md-4 {
        padding-top: 10px;
    }

    .btn-group.bootstrap-select > .btn.dropdown-toggle {
        padding: 6px;
    }
</style>

<div class="card">
    @this.Html.AntiForgeryToken()
    <div class="card-header">
        <div class="row">
            <div class="col-md-6">
                @if (this.Model.Id == 0)
                {
                    <h3 class="margin-bottom30">Tạo POS file</h3>
                }
                else
                {
                    <h3 class="margin-bottom30">Chỉnh sửa POS file: <strong>@this.Model.FileName</strong></h3>
                }
            </div>
            <div class="col-md-6 text-right">
                <ul class="actions">
                    <li class="m-r-10">
                        <a href="@this.Url.Action("Index", "PosFile")" class="btn btn-success myComeback">Quay lại</a>
                    </li>
                    <li>
                        <button type="button" class="btn btn-primary" id="btn-submit">Hoàn tất</button>
                    </li>
                </ul>
            </div>
        </div>
        <hr />
    </div>

    <div class="row">
        <div class="card-body card-padding">
            <div class="card">
                <div class="card-header">
                    <h2>Thông tin chính</h2>
                </div>
                <div class="card-body card-padding row">
                    <div class="col-md-6">
                        <div class="form-group row">
                            <label for="file-name" class="control-label col-md-4">Tên file</label>
                            <div class="col-md-8">
                                <div class="fg-line">
                                    <input class="form-control" value="@this.Model.FileName" id="file-name" name="file-name" />
                                </div>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="Product_Code" class="control-label col-md-4">Phiên bản</label>
                            <div class="col-md-8">
                                <div class="fg-line">
                                    <input class="form-control" value="@this.Model.Version" id="file-version" name="file-version" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group row">
                            <label for="Product_Code" class="control-label col-md-4">Thương hiệu</label>
                            <div class="col-md-8">
                                <div class="fg-line">
                                    <select class="selectpicker" id="brandId" title="Chọn 1 thương hiệu"></select>
                                </div>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="file-name" class="control-label col-md-4">Cửa hàng</label>
                            <div class="col-md-8">
                                <div class="fg-line">
                                    <select class="selectpicker" id="storeId" title="Chọn 1 cửa hàng"></select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <h2 class="col-md-2">POS config</h2>
                        @if (this.Model.Id == 0)
                        {
                            <div class="col-md-3 col-md-offset-6 p-r-20">
                                <div class="fg-line">
                                    <select class="selectpicker" id="config" title="Chọn 1 POS file mẫu"></select>
                                </div>
                            </div>
                            <div class="col-md-1">
                                <a href="#" class="btn btn-primary waves-effect pull-right" id="btn-clone">Sao chép</a>
                            </div>
                        }
                    </div>
                    <hr/>
                </div>
                <div class="card-body card-padding">
                    <div class="form-horizontal">
                        <div class="pair-panel">
                            @if (this.Model.PosConfigs != null)
                            {
                                foreach (var config in this.Model.PosConfigs)
                                {
                                    <div class="pair-group form-group xs-margin">
                                        <div class="col-sm-4">
                                            <div class="fg-line">
                                                <input type="text" class="form-control" name="config-key" placeholder="Key" value="@(config.Key)">
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="fg-line">
                                                <input type="text" class="form-control" name="config-value" placeholder="Value" value="@(config.Value)">
                                            </div>
                                        </div>
                                        <div class="col-sm-2">
                                            <button type="button" class="btn btn-danger form-control myForm" data-action="remove-pair-group">
                                                <i class="glyphicon glyphicon-trash"></i>
                                            </button>
                                        </div>
                                    </div>
                                }
                            }
                        </div>
                        <div class="form-group">
                            <div class="col-sm-12">
                                <button type="button" class="btn btn-info btn-icon-text waves-effect" data-action="add-pair-group">
                                    <i class="zmdi zmdi-plus"></i>Thêm
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Template Pair Group -->
<template id="templatePairGroup">
    <div class="pair-group form-group xs-margin">
        <div class="col-sm-4">
            <div class="fg-line">
                <input type="text" class="form-control" name="config-key" placeholder="Key" />
            </div>
        </div>
        <div class="col-sm-6">
            <div class="fg-line">
                <input type="text" class="form-control" name="config-value" placeholder="Value" />
            </div>
        </div>
        <div class="col-sm-2">
            <button type="button" class="btn btn-danger form-control myForm" data-action="remove-pair-group">
                <i class="glyphicon glyphicon-trash"></i>
            </button>
        </div>
    </div>
</template>

<!-- Template Photo Block -->
<template id="tmpPhotoBlock">
    <li class="col-md-4 photo-item removeable">
        <div class="ratio-wrapper ratio-wrapper-1-1">
            <div class="ratio-item">
                <div class="img-container">
                    <img />
                </div>
            </div>
        </div>
    </li>
</template>

<script>
    $(document).ready(function () {
        GetAllPosFile();

        var isCreating = '@(this.Model.Id == 0 ? "true" : "false")';

        if (isCreating == "true") {
            var brandList = @Html.Raw(Json.Encode(ViewBag.BrandList));

            var brandContent = "";

            for (var i = 0; i < brandList.length; i++) {
                brandContent += "<option value='" + brandList[i].Id + "'>" + brandList[i].Name + "</option>";
            }

            $('#brandId').html(brandContent);
            $('#brandId').val('');
            $('#storeId').val('');
            $('#brandId').selectpicker('refresh');
            $('#storeId').selectpicker('refresh');

            $('#brandId').on('change', function() {
                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("GetStoreList")',
                    data: {"brandId" : $('#brandId').val()},
                    success: function(result) {
                        if(result.success) {
                            var storeContent = "";

                            for (var i = 0; i < result.StoreList.length; i++) {
                                storeContent += "<option value='" + result.StoreList[i].ID + "'>" + result.StoreList[i].Name + "</option>";
                            }

                            $('#storeId').html(storeContent);
                            $('#storeId').val('');
                            $('#storeId').selectpicker('refresh');
                        } else {
                            ShowMessage(result.message, 3);
                        }
                    },
                    error: function() {
                        ShowMessage("Có lỗi xảy ra", 1);
                    }
                });
            });
        } else {
            $('#storeId').html("<option value='" + @(ViewBag.currentStore == null ? "" : ViewBag.currentStore.ID) + "'>" + '@(ViewBag.currentStore == null ? "" : ViewBag.currentStore.Name)' + "</option>");
            $('#brandId').html("<option value='" + @(ViewBag.currentBrand == null ? "" : ViewBag.currentBrand.Id) + "'>" + '@(ViewBag.currentBrand == null ? "" : ViewBag.currentBrand.BrandName)' + "</option>");
            $('#brandId').val(@(ViewBag.currentBrand == null ? "" : ViewBag.currentBrand.Id));
            $('#storeId').val(@(ViewBag.currentStore == null ? "" : ViewBag.currentStore.ID));
            $('#brandId').selectpicker('refresh');
            $('#storeId').selectpicker('refresh');
            $('#brandId').attr('disabled', 'disabled');
            $('#storeId').attr('disabled', 'disabled');
        }

        $('#btn-clone').on('click', function() {
            $.ajax ({
                url: '@Url.Action("GetAllConfig")',
                type: 'GET',
                data: { posFileId: $('#config').val() },
                success: function(result) {
                    if(result.success) {
                        $('.pair-panel').html('');
                        for(var i = 0; i < result.list.length; i++) {
                            var $newPairGroup = $('#templatePairGroup').html().trim();
                            $('.pair-panel').append($newPairGroup);
                            $('.pair-panel > .pair-group:nth-child(' + (i + 1) + ') input').first().val(result.list[i].Key);
                            $('.pair-panel > .pair-group:nth-child(' + (i + 1) + ') input').last().val(result.list[i].Value);
                        }
                        var $newPairGroup = $('#templatePairGroup').html().trim();
                        $('.pair-panel').append($newPairGroup);
                    }
                },
                error: function() {
                    ShowMessage("Có lỗi xảy ra", 1);
                }
            });
        });

        $('#btn-submit').parent().parent().css('z-index', '6');
        $('.myComeback').fixedScroll(70);
        $('#btn-submit').fixedScroll(70);
    });

    function GetAllPosFile() {
        $.ajax ({
            type: 'GET',
            url: '@Url.Action("GetAllPosFile")',
            success: function(result) {
                if(result.success) {
                    var fileContent = "";

                    for (var i = 0; i < result.list.length; i++) {
                        fileContent += "<option value='" + result.list[i][3] + "'>" + result.list[i][1] + "</option>";
                    }

                    $('#config').html(fileContent);
                    $('#config').val('');
                    $('#config').selectpicker('refresh');
                }
            },
            error: function() {

            }
        });
    }
</script>