Wisky.SkyAdmin.Manage/Wisky.SkyAdmin.Manage/Areas/Facebook/Controllers/VisitorController.cs
using Facebook;
using HmsService.Models;
using HmsService.Sdk;
using HmsService.ViewModels;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Wisky.SkyAdmin.Manage.Models;

namespace Wisky.SkyAdmin.Manage.Areas.Facebook.Controllers
{
    public class VisitorController : Controller
    {
        // GET: Facebook/Visitor
        StoreApi storeApi = new StoreApi();
        FacebookClient fbApp = new FacebookClient();
        CommentApi commentApi = new CommentApi();
        CustomerApi customerApi = new CustomerApi();
        public ActionResult Index(int storeId, int brandId)
        {
            if (storeId != 0)
            {
                var store = storeApi.Get(storeId);
                ViewBag.storeId = store.ID.ToString();
                ViewBag.storeName = store.Name;
                ViewBag.brandId = brandId;
                ViewBag.fbAppId = FacebookAppSetting.AppId;
                if (store.FbAccessToken != null)
                {
                    ViewBag.isConnected = true;
                    ViewBag.FbAccessToken = store.FbAccessToken;
                }
                else
                {
                    ViewBag.isConnected = false;
                };
                return View();
            }

            ViewBag.storeId = "0";
            ViewBag.storeName = "Tổng quan hệ thống";
            ViewBag.brandId = brandId;

            return View();
        }
        public JsonResult GetUserList(JQueryDataTableParamModel param, int storeId, DateTime? startDate, DateTime? endDate)
        {
            var shopId = storeApi.GetStoreById(storeId);
            var listUser = commentApi.GetCommentUserList(param, shopId.FbShopId, startDate, endDate);
            var totalRecords = listUser.Count();
            var data = listUser.Skip(param.iDisplayStart).Take(param.iDisplayLength).ToList();
            var displayRecords = data.Count();

            ShopViewModel shop = storeApi.GetShop(shopId.FbShopId);
            try
            {
                FacebookClient fbApp = new FacebookClient(shop.FbToken);
                dynamic fbUser;
                for (int i = 0; i < data.Count(); i++)
                {
                    try
                    {
                        fbUser = System.Web.Helpers.Json.Decode(fbApp.Get(data[i].UserFBId).ToString());
                        data[i].UserName = fbUser.name;
                        try
                        {
                            CustomerViewModel registedCustomer = customerApi.GetCustomerByFacebookId(data[i].UserFBId, shopId.FbShopId);
                            if (registedCustomer.Name != null)
                            {
                                data[i].IsCustomer = true;
                                data[i].UserName = data[i].UserName + " (" + registedCustomer.Name + ")";
                            }
                        }
                        catch (Exception)
                        {
                            data[i].IsCustomer = false;
                        }
                    }
                    catch (Exception ex)
                    {
                        data[i].UserName = "Người dùng không tồn tại";
                        Debug.WriteLine(ex.Message);
                    }
                }
                var dataList = data.Select(q => new {
                    q.UserName,
                    q.TotalComment,
                    q.UnreadComment,
                    q.ListIntentNumber,
                    q.ListStatusNumber,
                    q.UserFBId,
                });
                return Json(new
                {
                    sEcho = param.sEcho,
                    iTotalRecords = totalRecords,
                    iTotalDisplayRecords = totalRecords,//displayRecords,
                    aaData = dataList,
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                Debug.WriteLine(e.Message);
                return null;
            }


        }
    }
}

Wisky.SkyAdmin.Manage/Wisky.SkyAdmin.Manage/Areas/Facebook/Views/Visitor/Index.cshtml
@{
    ViewBag.Title = "Quản lý bài đăng";
    var storeId = ViewBag.storeId;
    var storeName = ViewBag.storeName;
    var brandId = ViewBag.brandId;


    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<style>
    .table {
        width: 100% !important;
    }

    .leftTable {
        text-align: left !important;
    }

    .table > thead > tr > th {
        border: 0.1px solid #00b743 !important;
        font-weight: normal !important;
    }

    .col-sm-2 {
        width: 19% !important;
    }

    .m-b-25 {
        margin-bottom: 0px !important;
    }

    .card .card-body {
        padding-top: 0px;
    }
    #tblVisitor_filter {
        display: none;
    }

    #selectAllButtonPostTbl {
        font-size: large;
    }
</style>
<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-md-8">
                <h3 id="titlePage">Thống kê bài đăng theo người sử dụng</h3>
            </div>
        </div>
        <hr />
    </div>

    <div class="card-body">
        <div role="tabpanel" class="tab">
            <!--Tab content-->
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane animated fadeIn active" id="post">
                    <div class="" id="filter-container" style="margin-bottom:10px; margin-right:10px">
                        <div class="row">
                            <div class="input-group pull-right" style="padding-top:10px">
                                <div class="dateTime width230 pull-right">
                                    <div class="fg-line m-t-5">
                                        <div id="reportrange">
                                            <input id="date-string" readonly class="form-control text-center">
                                            <a class="myCelenderA" id=""><i class="fa fa-calendar"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <input type="hidden" id="sTime" />
                            <input type="hidden" id="eTime" />
                        </div>
                    </div>
                    <!--./Filter condition-->
                    <!--Post table-->
                    <div class="card-padding">
                        <table id="tblVisitor" class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>Tên người dùng</th>
                                    <th>Tổng bình luận</th>
                                    <th>Đánh giá</th>
                                    <th>Chưa đọc</th>
                                    <th>Mục đích</th>
                                    <th>Trạng thái</th>
                                    <th>Thao tác</th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                    <!--./ Post table-->
                </div>
            </div>
            <!--./Tab content-->
        </div>
    </div>
</div>

<script>
    
    $(document).ready(function () {
        InitPostTable();
        function cb(start, end, label) {
            var startTime = start.format("MM/DD/YYYY"),
                endTime = end.format("MM/DD/YYYY"),
                dateString = "(" + startTime + (startTime == endTime ? "" : " - " + endTime) + ")";

            if (label != "Tùy chọn") {
                $('#date-string').val(label);
            } else {
                $("#date-string").val(dateString);
            }

            $("#sTime").val(startTime);
            $("#eTime").val(endTime);
            $("#dateRange").html(dateString);
            RefreshTable();
        }
        cb(moment(), moment(), "Hôm nay");

        $('#reportrange').daterangepicker({
            "opens": "left",
            "maxDate": moment(),
            locale: {
                format: 'DD/MM/YYYY'
            },
            ranges: {
                'Hôm nay': [moment(), moment()],
                'Hôm qua': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                'Tuần này': [moment().startOf('isoweek'), moment().endOf('isoweek')],
                'Tuần trước': [moment().subtract(1, 'week').startOf('isoweek'), moment().subtract(1, 'week').endOf('isoweek')],
                'Tháng này': [moment().startOf('month'), moment().endOf('month')],
                'Tháng trước': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
            }
        }, cb);
    });
    function InitPostTable() {
        $("#tblVisitor").dataTable({
            "oLanguage": {
                "sZeroRecords": "Không có dữ liệu phù hợp",
                "sInfo": "Hiển thị từ _START_ đến _END_ trên tổng số _TOTAL_ dòng",
                "sEmptyTable": "Không có dữ liệu",
                "sInfoFiltered": " - lọc ra từ _MAX_ dòng",
                "sLengthMenu": "Hiển thị _MENU_ dòng",
                "sProcessing": "Đang xử lý...",
                "oPaginate": {
                    "sNext": "<i class='fa fa-chevron-right'></i>",
                    "sPrevious": "<i class='fa fa-chevron-left'></i>"
                }
            },
            "bProcessing": true,
            "bSort": false,
            "bServerSide": true,
            "sAjaxSource": "@Url.Action("GetUserList", "Visitor")",
            "fnServerParams": function (aoData) {
                aoData.push({ "name": "endDate", "value": $('#eTime').val().concat(" 23:59:59.000") });
                aoData.push({ "name": "startDate", "value": $('#sTime').val() });
            },
            "aoColumnDefs": [
                 {
                     "aTargets": [0],
                     "mRender": function (data, type, row) {
                         return "<a href ='https://www.facebook.com/" + row.UserFBId + "' target='_blank'>" + row.UserName + "</a>";
                     },
                     "width": " 15%"
                 },
                 {
                     "aTargets": [1],
                     "mRender": function (data, type, row) {
                         return row.TotalComment;
                     }, "sClass": "text-center", "width": "10%"
                 },
                 {
                     "aTargets": [2],
                     "mRender": function (data, type, row) {
                         return row.TotalComment * 3;
                     }, "sClass": "text-center", "width": "10%"
                 },
                 {
                     "aTargets": [3],
                     "mRender": function (data, type, row) {
                         return row.UnreadComment;
                     }, "sClass": "text-center", "width": "10%"
                 },
                 {
                     "aTargets": [4],
                     "mRender": function (data, type, row) {
                         //return row.ListIntentNumber;
                         return "Chưa có dữ liệu";
                     }, "width": "25%"
                 },
                 {
                     "aTargets": [5],
                     "mRender": function (data, type, row) {
                         var StatusName = "";
                         var dataLength = row.ListStatusNumber.length;
                         for (var i = 0; i < dataLength; i++) {
                             StatusName = StatusName + row.ListStatusNumber[i].StatusName + " : " + row.ListStatusNumber[i].StatusCount + " || ";
                         }
                         return StatusName;
                     }
                 },
                 {
                     "aTargets": [6],
                     "mRender": function (data, type, row) {
                         var button = "<a onclick='alert(\"" + row.UserFBId + "\")'><span class='btn btn-sm btn-info'>Test</span></a>";
                         return button;
                     }, "width": "8%"
                 },
            ],

        });
    }

    function reDrawDatatable(id) {
        $.fn.dataTableExt.oApi.fnStandingRedraw = function (oSettings) {
            if (oSettings.oFeatures.bServerSide === false) {
                var before = oSettings._iDisplayStart;
                oSettings.oApi._fnReDraw(oSettings);
                //iDisplayStart has been reset to zero - so lets change it back
                oSettings._iDisplayStart = before;
                oSettings.oApi._fnCalculateEnd(oSettings);
            }
            //draw the 'current' page
            oSettings.oApi._fnDraw(oSettings);
        };
        $(id).dataTable().fnStandingRedraw();
    }

    //user datatable
    function RefreshTable() {
        reDrawDatatable("#tblVisitor");
    }
</script>