Wisky.SkyUp/Wisky.SkyUp.Website/Areas/PosReport/Controllers/SystemReportController.cs
using HmsService.Models;
using HmsService.Sdk;
using HmsService.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using SkyWeb.DatVM.Mvc;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
//using System.Windows.Forms;
using Wisky.SkyUp.Website.Areas.PosReport.Models;

namespace Wisky.SkyUp.Website.Areas.PosReport.Controllers
{
    public class SystemReportController : BaseController
    {
        // GET: PosReport/SystemReport
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult RevenueReport()
        {
            return View();
        }

        public JsonResult LoadRevenueReport(JQueryDataTableParamModel param, string startTime, string endTime, int brandId)
        {
            var listDateReport = new List<TempSystemRevenueReportItem>();

            var storeApi = new StoreApi();
            var dateReportApi = new DateReportApi();

            var today = DateTime.Now.ToString("dd/MM/yyyy");
            try
            {
                if (startTime == "" || endTime == "")
                {
                    // 1. get ngay (ngày đầu tháng -> ngày hiện tại)
                    var dateNow = DateTime.Now;
                    var startDate = new DateTime(dateNow.Year, dateNow.Month, 1);
                    var tempStartDate = startDate;
                    var endDate = dateNow.GetEndOfDate();
                    // 2. lấy list store
                    var storeList = storeApi.GetActiveStoreByBrandId(brandId)
                        .Where(a => string.IsNullOrEmpty(param.sSearch) || a.Name.ToLower().Contains(param.sSearch))
                        .OrderBy(a => a.Name).ToList();
                    // 3. duyệt ngày theo store -> lấy dc doanh thu của ngày theo tất cả cửa hàng
                    for (var d = startDate; startDate <= endDate; d.AddDays(1))
                    {
                        double totalDateAmount = 0;
                        double finalDateAmount = 0;
                        double discountDateFee = 0;
                        foreach (var store in storeList)
                        {
                            var dateReport = dateReportApi.GetDateReportTimeRangeAndStore(startDate, startDate.GetEndOfDate(), store.ID).ToList();

                            var totalAmount = (double)dateReport.Sum(a => a.TotalAmount);
                            var finalAmount = (double)dateReport.Sum(a => a.FinalAmount);
                            var discountFee = (double)dateReport.Sum(a => a.Discount) + (double)dateReport.Sum(a => a.DiscountOrderDetail);

                            totalDateAmount += totalAmount;
                            finalDateAmount += finalAmount;
                            discountDateFee += discountFee;
                        }
                        listDateReport.Add(new TempSystemRevenueReportItem()
                        {
                            StartTime = startDate.ToString("dd/MM/yyyy"),
                            TotalAmount = totalDateAmount,
                            FinalAmount = finalDateAmount,
                            TotalDiscountFee = discountDateFee
                        });
                        startDate = startDate.AddDays(1);
                    }
                }
                else
                {
                    var startDate = DateTime.Parse(startTime).GetStartOfDate();
                    var endDate = DateTime.Parse(endTime).GetEndOfDate();
                    // 1. get ngay (ngày đầu tháng -> ngày hiện tại)
                    var dateNow = DateTime.Now;
                    var tempStartDate = startDate;
                    // 2. lấy list store
                    var storeList = storeApi.GetActiveStoreByBrandId(brandId)
                        .Where(a => string.IsNullOrEmpty(param.sSearch) || a.Name.ToLower().Contains(param.sSearch))
                        .OrderBy(a => a.Name);
                    // 3. duyệt ngày theo store -> lấy dc doanh thu của ngày theo tất cả cửa hàng
                    for (var d = startDate; startDate <= endDate; d.AddDays(1))
                    {
                        double totalDateAmount = 0;
                        double finalDateAmount = 0;
                        double discountDateFee = 0;
                        foreach (var store in storeList)
                        {
                            var dateReport = dateReportApi.GetDateReportTimeRangeAndStore(startDate, startDate.GetEndOfDate(), store.ID).ToList();

                            var totalAmount = (double)dateReport.Sum(a => a.TotalAmount);
                            var finalAmount = (double)dateReport.Sum(a => a.FinalAmount);
                            var discountFee = (double)dateReport.Sum(a => a.Discount) + (double)dateReport.Sum(a => a.DiscountOrderDetail);

                            totalDateAmount += totalAmount;
                            finalDateAmount += finalAmount;
                            discountDateFee += discountFee;

                        }
                        listDateReport.Add(new TempSystemRevenueReportItem()
                        {
                            StartTime = startDate.ToString("dd/MM/yyyy"),
                            TotalAmount = totalDateAmount,
                            FinalAmount = finalDateAmount,
                            TotalDiscountFee = discountDateFee
                        });
                        startDate = startDate.AddDays(1);
                    }
                }
                var list = listDateReport.Select(a => new IConvertible[]
                        {
                        a.StartTime,
                        string.Format(CultureInfo.InvariantCulture,
                           "{0:0,0}", a.TotalAmount),
                        string.Format(CultureInfo.InvariantCulture,
                           "{0:0,0}", a.TotalDiscountFee),
                        string.Format(CultureInfo.InvariantCulture,
                           "{0:0,0}", a.FinalAmount)
                        }).ToArray();

                //var totalRecords = await customerStores.CountAsync();
                var totalRecords = 10;

                //return Json(new
                //{
                //    sEcho = param.sEcho,
                //    iTotalRecords = totalRecords,
                //    iTotalDisplayRecords = list.Count(),
                //    aaData = list
                //}, JsonRequestBehavior.AllowGet);

                return Json(new
                {
                    dataList = list
                }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception e)
            {
                return Json(new { success = false });
            }
        }

        public ActionResult ExportRevenueTableToExcel(JQueryDataTableParamModel param, string startTime, string endTime, int brandId)
        {
            var listDateReport = new List<TempSystemRevenueReportItem>();
            var storeApi = new StoreApi();
            var dateReportApi = new DateReportApi();

            var today = DateTime.Now.ToString("dd/MM/yyyy");
            if (startTime == "" || endTime == "")
            {
                // 1. get ngay (ngày đầu tháng -> ngày hiện tại)
                var dateNow = DateTime.Now;
                var startDate = new DateTime(dateNow.Year, dateNow.Month, 1);
                var tempStartDate = startDate;
                var endDate = dateNow.GetEndOfDate();
                // 2. lấy list store
                var storeList = storeApi.GetActiveStoreByBrandId(brandId)
                    .Where(a => string.IsNullOrEmpty(param.sSearch) || a.Name.ToLower().Contains(param.sSearch))
                    .OrderBy(a => a.Name).ToList();
                // 3. duyệt ngày theo store -> lấy dc doanh thu của ngày theo tất cả cửa hàng
                for (var d = startDate; startDate <= endDate; d.AddDays(1))
                {
                    double totalDateAmount = 0;
                    double finalDateAmount = 0;
                    double discountDateFee = 0;
                    foreach (var store in storeList)
                    {
                        var dateReport = dateReportApi.GetDateReportTimeRangeAndStore(startDate, startDate.GetEndOfDate(), store.ID).ToList();

                        var totalAmount = (double)dateReport.Sum(a => a.TotalAmount);
                        var finalAmount = (double)dateReport.Sum(a => a.FinalAmount);
                        var discountFee = (double)dateReport.Sum(a => a.Discount) + (double)dateReport.Sum(a => a.DiscountOrderDetail);

                        totalDateAmount += totalAmount;
                        finalDateAmount += finalAmount;
                        discountDateFee += discountFee;
                    }
                    listDateReport.Add(new TempSystemRevenueReportItem()
                    {
                        StartTime = startDate.ToString("dd/MM/yyyy"),
                        TotalAmount = totalDateAmount,
                        FinalAmount = finalDateAmount,
                        TotalDiscountFee = discountDateFee
                    });
                    startDate = startDate.AddDays(1);
                }
            }
            else
            {
                var startDate = DateTime.Parse(startTime).GetStartOfDate();
                var endDate = DateTime.Parse(endTime).GetEndOfDate();
                // 1. get ngay (ngày đầu tháng -> ngày hiện tại)
                var dateNow = DateTime.Now;
                var tempStartDate = startDate;
                // 2. lấy list store
                var storeList = storeApi.GetActiveStoreByBrandId(brandId)

Wisky.SkyUp/Wisky.SkyUp.Website/Areas/PosReport/Views/SystemReport/RevenueReport.cshtml
@{
    ViewBag.Title = "Báo cáo doanh thu";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-content">
    <div class="page-header">
        <div class="row">
            <div class="col-md-8">
                <h1>Báo cáo doanh thu tháng<small data-role="small-date" id="dateRange"></small></h1>
            </div>
            <div class="col-md-4 text-right">
                <div class="input-group">
                    <div class="date-picker">
                        <input type="text" id="date-string" readonly="">
                        <a id="reportrange"><i class="fa fa-calendar"></i></a>
                    </div><!-- /input-group -->
                    <div class="input-group-btn">
                        <a class="btn btn-success btn-sm" id="btnSearch">
                            <i class="left-icon fa fa-search"></i>Tìm
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <input type="text" id="sTime" name="startTime" placeholder="Chọn giờ bắt đầu" hidden="hidden" />
        <input type="text" id="eTime" name="endTime" placeholder="Chọn giờ kết thúc" hidden="hidden" />
    </div>

    <!-- export to excel -->
    <div style="margin-right:15px;">
        <button type="submit" id="export" class="btn btn-success btn-sm">
            <i class="fa fa-download"></i>
            Xuất ra file Excel
        </button>
    </div>

    <div id="datatable">
        <table id="systemReportDatatable" class="table table-striped table-bordered table-hover" style="width: 100% !important">
            <thead style="white-space: nowrap; text-overflow: ellipsis;">
                <tr>
                    <th>
                        <label class="">Ngày</label>
                    </th>
                    <th>
                        <label class="">Tổng doanh thu</label>
                    </th>
                    <th>
                        <label class="">Giảm giá</label>
                    </th>
                    <th>
                        <label class="">Doanh thu sau giảm giá</label>
                    </th>
                </tr>
            </thead>
            <tbody></tbody>
            <tfoot>
                <tr>
                    <th style="text-align:right">Tổng tất cả các ngày:</th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
            </tfoot>
        </table>

    </div>
</div>

<script>
    $(document).ready(function () {
        cb(moment().startOf('month'), moment(), "Tháng này");

        setupDaterangepicker();

        dataReport();
    });

    var numberWithSeparator = function (x) {
        return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")
    };

    var dataReport = function () {
        $.ajax({
            type: 'GET',
            url: '@Url.Action("LoadRevenueReport","SystemReport")',
            data: { 'startTime': $('#sTime').val(), 'endTime': $('#eTime').val() },
            success: function (result) {

                initRevenueDatatable(result.dataList);
            }
        });
    };

    var initRevenueDatatable = function (datalist) {
        // Reset table
        $("#datatable").html("<table id=\"systemReportDatatable\" class=\"table table-striped table-bordered table-hover\" style=\"width: 100% !important\">"
                    + "<thead style=\"white-space: nowrap; text-overflow: ellipsis;\">"
                        + "<tr>"
                            + "<th>"
                                + "<label class=\"\">Ngày</label>"
                            + "</th>"
                            + "<th>"
                                + "<label class=\"\">Tổng doanh thu</label>"
                            + "</th>"
                            + "<th>"
                                + "<label class=\"\">Giảm giá</label>"
                            + "</th>"
                            + "<th>"
                                + "<label class=\"\">Doanh thu sau giảm giá</label>"
                            + "</th>"
                        + "</tr>"
                    + "</thead>"
                    + "<tbody></tbody>"
                    + "<tfoot>"
                        + "<tr>"
                            + "<th style=\"text-align:right\">Tổng tất cả các ngày:</th>"
                            + "<th></th>"
                            + "<th></th>"
                            + "<th></th>"
                        + "</tr>"
                    + "</tfoot>"
                + "</table>");

        // Inite new datatable
        $("#systemReportDatatable").DataTable({
            "footerCallback": function (row, data, start, end, display) {
                var api = this.api(), data;

                // Remove the formatting to get integer data for summation
                var intVal = function (i) {
                    return typeof i === 'string' ?
                        i.replace(/[\$,]/g, '') * 1 :
                        typeof i === 'number' ?
                        i : 0;
                };

                // Total over all pages
                totalIncome = api
                    .column(1)
                    .data()
                    .reduce(function (a, b) {
                        return intVal(a) + intVal(b);
                    }, 0);

                totalDiscount = api
                    .column(2)
                    .data()
                    .reduce(function (a, b) {
                        return intVal(a) + intVal(b);
                    }, 0)

                totalFinalIncome = api
                    .column(3)
                    .data()
                    .reduce(function (a, b) {
                        return intVal(a) + intVal(b);
                    }, 0)
                var cells = row.getElementsByTagName('th');
                cells[1].innerHTML = numberWithSeparator(totalIncome);
                cells[2].innerHTML = numberWithSeparator(totalDiscount);
                cells[3].innerHTML = numberWithSeparator(totalFinalIncome);
            },
            "bFilter": false,
            "bSort": false,
            "bRetrieve": true,
            "bScrollCollapse": true,
            "data": datalist,
            "iDisplayLength": 50,
            "aLengthMenu": [50, 100],
            "oLanguage": {
                "sSearch": "Tìm kiếm:",
                "sZeroRecords": "Không có dữ liệu phù hợp",
                "sInfo": "Hiển thị từ _START_ đến _END_ trên tổng số _TOTAL_ dòng",
                "sEmptyTable": "Không có dữ liệu",
                "sInfoFiltered": " - lọc ra từ _MAX_ dòng",
                "sLengthMenu": "Hiển thị _MENU_ dòng",
                "sProcessing": "Đang xử lý..."
            },
            "aoColumnDefs": [
                {

                },
            ],
            "bAutoWidth": false
        });
    };

    $('#btnSearch').on('click', function () {
        if ($("#eTime").val().length > 16 || $("#sTime").val().length > 16) {
            ShowMessage("Vui lòng nhập thời gian đúng định dạng", 3);
            return;
        }
        else {
            dataReport();
        }
    });

    // Export to excel
    $("#export").on('click', function () {
        $.ajax({
            url: '@Url.Action("ExportRevenueTableToExcel","SystemReport")',
            type: 'GET',
            data: { 'startTime': $('#sTime').val(), 'endTime': $('#eTime').val() },
            success: function (rs) {
                if (rs.success == true) {
                    ShowMessage('Xuất file Excel thành công <br/>' + rs.fileName, 3);
                } else {
                    ShowMessage('Xuất file Excel thất bại', 1);
                }
            }
        });
    });

    function cb(start, end, label) {
        var startTime = start.format("DD/MM/YYYY"),
            endTime = end.format("DD/MM/YYYY"),
            dateString = "(" + startTime + (startTime == endTime ? "" : " - " + endTime) + ")";

        if (label != "Custom Range") {
            $('#date-string').val(label);
        } else {
            $("#date-string").val(dateString);
        }

        $("#sTime").val(startTime);
        $("#eTime").val(endTime);
        $("#dateRange").html(dateString);
    }

    //init dateRange picker
    function setupDaterangepicker() {
        $('#reportrange').daterangepicker({
            "opens": "left",
            "maxDate": moment(),
            locale: {
                format: 'DD/MM/YYYY'
            },
            ranges: {
                'Tháng này': [moment().startOf('month'), moment().endOf('month')],
                'Tháng trước': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
            }
        }, cb);
    }
</script>